name: Metrics
on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta cada medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Usa tu PAT para la API y para hacer el commit
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          
          # Configuración de lenguajes
          plugin_languages: yes
          plugin_languages_details: percentage, bytes-size
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
